package startup

import (
	"fmt"
	unitmodel "honoka-chan/internal/model/unit"
	usermodel "honoka-chan/internal/model/user"
	"honoka-chan/pkg/db"
	"log"
	"time"

	"xorm.io/xorm"
)

// ReconcileLegacyOwnershipReferences translates persisted Termux-era
// unit_owning_user_id values to the IDs generated by the current mainline.
//
// The working Termux core populated common_unit_m in its database's natural
// row order, starting ownership IDs at 38383. The current mainline populates
// user_unit_data ordered by unit_id. Therefore the same numeric ownership ID
// can refer to a different card after an in-place upgrade. Decks, centre-unit
// preferences, accessory wear and removable-skill equipment all persist those
// IDs, so merely renaming tables is not sufficient and can make the native CN
// client abort while consuming the login batch response.
func ReconcileLegacyOwnershipReferences() {
	session := db.UserEng.NewSession()
	defer session.Close()

	if err := session.Begin(); err != nil {
		log.Fatalln("开始旧版卡片引用迁移失败:", err.Error())
	}
	if err := reconcileLegacyOwnershipReferences(session); err != nil {
		_ = session.Rollback()
		log.Fatalln("迁移旧版卡片引用失败:", err.Error())
	}
	if err := session.Commit(); err != nil {
		_ = session.Rollback()
		log.Fatalln("提交旧版卡片引用迁移失败:", err.Error())
	}
}

func reconcileLegacyOwnershipReferences(session *xorm.Session) error {
	userIDs := []int{}
	if err := session.Table(new(usermodel.Users)).
		Where("user_id IS NOT NULL AND user_id > 0").
		Cols("user_id").
		OrderBy("user_id ASC").
		Find(&userIDs); err != nil {
		return fmt.Errorf("读取用户列表失败: %w", err)
	}
	if len(userIDs) == 0 {
		return nil
	}

	commonUnits := []unitmodel.CommonUnitData{}
	if err := session.Table(new(unitmodel.CommonUnitData)).OrderBy("unit_id ASC").Find(&commonUnits); err != nil {
		return fmt.Errorf("读取 common_unit_data 失败: %w", err)
	}
	if len(commonUnits) == 0 {
		return nil
	}
	commonByUnitID := make(map[int]unitmodel.CommonUnitData, len(commonUnits))
	for _, row := range commonUnits {
		commonByUnitID[row.UnitID] = row
	}

	occupied := map[int]struct{}{}
	allOwningIDs := []int{}
	if err := session.Table(new(usermodel.UserUnitData)).Cols("unit_owning_user_id").Find(&allOwningIDs); err != nil {
		return fmt.Errorf("读取 unit_owning_user_id 失败: %w", err)
	}
	for _, id := range allOwningIDs {
		if id > 0 {
			occupied[id] = struct{}{}
		}
	}

	for _, userID := range userIDs {
		legacyPrefs, err := loadLegacyUnitPreferences(session, userID)
		if err != nil {
			return err
		}
		unitByID, unitByOwningID, _, _, err := ensureUserUnitMappings(
			session, userID, commonUnits, legacyPrefs, occupied,
		)
		if err != nil {
			return err
		}

		translation := make(map[int]int, len(legacyCommonUnitOrder)+len(legacyPrefs))
		for index, unitID := range legacyCommonUnitOrder {
			if current, ok := unitByID[unitID]; ok {
				translation[legacyCommonOwningBase+index] = current.UnitOwningUserID
			}
		}

		customRows, err := ensureLegacyCustomUnitRows(session, userID, commonByUnitID, unitByOwningID, occupied)
		if err != nil {
			return err
		}
		for oldID, current := range customRows {
			translation[oldID] = current.UnitOwningUserID
			unitByOwningID[current.UnitOwningUserID] = current
			if _, exists := unitByID[current.UnitID]; !exists {
				unitByID[current.UnitID] = current
			}
		}

		changed, err := translateLegacyCenter(session, userID, translation, unitByID)
		if err != nil {
			return err
		}
		decks, err := translateLegacyDecks(session, userID, translation, unitByID, commonByUnitID)
		if err != nil {
			return err
		}
		links, err := translateLegacyLinkedUnitReferences(session, userID, translation)
		if err != nil {
			return err
		}
		if changed || decks > 0 || links > 0 || len(customRows) > 0 {
			log.Printf("用户 %d 旧版卡片引用迁移完成: 自定义卡=%d, 卡组=%d, 关联引用=%d, 中心成员修复=%t", userID, len(customRows), decks, links, changed)
		}
	}
	return nil
}

func ensureLegacyCustomUnitRows(
	session *xorm.Session,
	userID int,
	commonByUnitID map[int]unitmodel.CommonUnitData,
	currentByOwning map[int]usermodel.UserUnitData,
	occupied map[int]struct{},
) (map[int]usermodel.UserUnitData, error) {
	hasLegacy, err := db.UserEng.IsTableExist("user_unit_m")
	if err != nil || !hasLegacy {
		return map[int]usermodel.UserUnitData{}, err
	}
	legacyRows := []legacyUserUnit{}
	if err := session.Table("user_unit_m").Where("user_id = ?", userID).OrderBy("unit_owning_user_id ASC").Find(&legacyRows); err != nil {
		return nil, fmt.Errorf("读取用户 %d 的 user_unit_m 失败: %w", userID, err)
	}

	result := make(map[int]usermodel.UserUnitData, len(legacyRows))
	for _, legacy := range legacyRows {
		if legacy.UnitOwningUserID <= 0 || legacy.UnitID <= 0 {
			continue
		}
		desiredOwningID := legacy.UnitOwningUserID
		for attempt := 0; attempt < 8; attempt++ {
			candidate := legacy.UnitOwningUserID + attempt*100000000
			if current, ok := currentByOwning[candidate]; ok && current.UserID == userID && current.UnitID == legacy.UnitID {
				result[legacy.UnitOwningUserID] = current
				desiredOwningID = 0
				break
			}
			if _, used := occupied[candidate]; !used {
				desiredOwningID = candidate
				break
			}
		}
		if _, alreadyResolved := result[legacy.UnitOwningUserID]; alreadyResolved {
			continue
		}
		common, ok := commonByUnitID[legacy.UnitID]
		if !ok {
			continue
		}
		row := usermodel.UserUnitData{
			UnitID:       legacy.UnitID,
			FavoriteFlag: legacy.FavoriteFlag != 0,
			DisplayRank:  legacy.DisplayRank,
			UserID:       userID,
			InsertDate:   time.Now().Unix(),
		}
		if row.DisplayRank <= 0 {
			row.DisplayRank = common.MaxRank
		}
		if desiredOwningID <= 0 {
			return nil, fmt.Errorf("无法为用户 %d 的旧卡片 owning=%d 分配稳定的新 ownership ID", userID, legacy.UnitOwningUserID)
		}
		row.UnitOwningUserID = desiredOwningID
		if _, err := session.Insert(&row); err != nil {
			return nil, fmt.Errorf("迁移用户 %d 的自定义卡片 owning=%d unit=%d 失败: %w", userID, legacy.UnitOwningUserID, legacy.UnitID, err)
		}
		occupied[row.UnitOwningUserID] = struct{}{}
		result[legacy.UnitOwningUserID] = row
	}
	return result, nil
}

func translateLegacyCenter(
	session *xorm.Session,
	userID int,
	translation map[int]int,
	unitByID map[int]usermodel.UserUnitData,
) (bool, error) {
	hasLegacy, err := db.UserEng.IsTableExist("user_preference_m")
	if err != nil || !hasLegacy {
		return false, err
	}
	legacy := legacyUserPreference{}
	has, err := session.Table("user_preference_m").Where("user_id = ?", userID).Get(&legacy)
	if err != nil || !has {
		return false, err
	}
	newID := translation[legacy.UnitOwningUserID]
	if newID <= 0 {
		if unitID, ok := legacyCommonOwningToUnitID(legacy.UnitOwningUserID); ok {
			newID = unitByID[unitID].UnitOwningUserID
		}
	}
	if newID <= 0 {
		return false, nil
	}
	pref := usermodel.UserPref{}
	has, err = session.Table(new(usermodel.UserPref)).Where("user_id = ?", userID).Get(&pref)
	if err != nil || !has || pref.UnitOwningUserID == newID {
		return false, err
	}
	pref.UnitOwningUserID = newID
	_, err = session.Table(new(usermodel.UserPref)).Where("user_id = ?", userID).Cols("unit_owning_user_id").Update(&pref)
	return err == nil, err
}

func translateLegacyDecks(
	session *xorm.Session,
	userID int,
	translation map[int]int,
	unitByID map[int]usermodel.UserUnitData,
	commonByUnitID map[int]unitmodel.CommonUnitData,
) (int, error) {
	hasDecks, err := db.UserEng.IsTableExist("user_deck_m")
	if err != nil || !hasDecks {
		return 0, err
	}
	hasUnits, err := db.UserEng.IsTableExist("deck_unit_m")
	if err != nil || !hasUnits {
		return 0, err
	}
	legacyDecks := []legacyUserDeck{}
	if err := session.Table("user_deck_m").Where("user_id = ?", userID).Find(&legacyDecks); err != nil {
		return 0, err
	}
	changed := 0
	for _, legacyDeck := range legacyDecks {
		currentDeck := usermodel.UserDeck{}
		has, err := session.Table(new(usermodel.UserDeck)).Where("user_id = ? AND deck_id = ?", userID, legacyDeck.DeckID).Get(&currentDeck)
		if err != nil || !has {
			if err != nil {
				return changed, err
			}
			continue
		}
		legacyUnits := []legacyDeckUnit{}
		if err := session.Table("deck_unit_m").Where("user_deck_id = ?", legacyDeck.ID).OrderBy("position ASC").Find(&legacyUnits); err != nil {
			return changed, err
		}
		for _, old := range legacyUnits {
			newID := translation[old.UnitOwningUserID]
			userUnit := usermodel.UserUnitData{}
			if newID > 0 {
				_, err = session.Table(new(usermodel.UserUnitData)).Where("user_id = ? AND unit_owning_user_id = ?", userID, newID).Get(&userUnit)
				if err != nil {
					return changed, err
				}
			}
			if userUnit.UnitOwningUserID <= 0 && old.UnitID > 0 {
				userUnit = unitByID[old.UnitID]
			}
			common, ok := commonByUnitID[userUnit.UnitID]
			if userUnit.UnitOwningUserID <= 0 || !ok {
				continue
			}
			corrected := buildDeckUnit(currentDeck.ID, userID, old.Position, resolvedDeckUnit{UserUnit: userUnit, Common: common})
			row := usermodel.UserDeckUnit{}
			has, err := session.Table(new(usermodel.UserDeckUnit)).Where("user_deck_id = ? AND position = ?", currentDeck.ID, old.Position).Get(&row)
			if err != nil {
				return changed, err
			}
			if has {
				corrected.ID = row.ID
				if _, err := session.Table(new(usermodel.UserDeckUnit)).ID(row.ID).AllCols().Update(&corrected); err != nil {
					return changed, err
				}
			} else if _, err := session.Insert(&corrected); err != nil {
				return changed, err
			}
			changed++
		}
	}
	return changed, nil
}

func translateLegacyLinkedUnitReferences(session *xorm.Session, userID int, translation map[int]int) (int, error) {
	changed := 0
	for oldID, newID := range translation {
		if oldID <= 0 || newID <= 0 || oldID == newID {
			continue
		}
		res, err := session.Exec("UPDATE user_unit_skill_equip SET unit_owning_user_id = ? WHERE user_id = ? AND unit_owning_user_id = ?", newID, userID, oldID)
		if err != nil {
			return changed, err
		}
		if n, _ := res.RowsAffected(); n > 0 {
			changed += int(n)
		}
		res, err = session.Exec("UPDATE user_accessory_wear SET unit_owning_user_id = ? WHERE user_id = ? AND unit_owning_user_id = ?", newID, userID, oldID)
		if err != nil {
			return changed, err
		}
		if n, _ := res.RowsAffected(); n > 0 {
			changed += int(n)
		}
	}
	return changed, nil
}
